# Generated by Django 5.2.5 on 2026-04-08 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('score', 'Score'), ('length', 'Length'), ('best_combo', 'Best Combo')], max_length=20)),
                ('player_id', models.UUIDField(default=uuid.uuid4)),
                ('player_name', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
                ('achieved_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['board_type', '-value', 'achieved_at'], name='idx_lb_board_val_time')],
                'constraints': [models.UniqueConstraint(fields=('board_type', 'player_id'), name='uniq_board_player')],
            },
        ),
    ]
